//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.03.25 at 03:40:09 PM NZDT
//


package nz.co.ctg.jmsfx.svg.shape;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.google.common.base.MoreObjects.ToStringHelper;

import javafx.scene.shape.Ellipse;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ellipse")
@XmlRootElement(name = "ellipse")
public class FXVGEllipse extends AbstractFXVGShape implements FXVGShape<Ellipse> {

    @XmlAttribute(name = "cx")
    protected double centreX;

    @XmlAttribute(name = "cy")
    protected double centreY;

    @XmlAttribute(name = "rx", required = true)
    protected double radiusX;

    @XmlAttribute(name = "ry", required = true)
    protected double radiusY;

    @Override
    public Ellipse createShape() {
        Ellipse ellipse = new Ellipse(centreY, centreX, radiusX, radiusY);
        return ellipse;
    }

    /**
     * Gets the value of the cx property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getCentreX() {
        return centreX;
    }

    /**
     * Gets the value of the cy property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getCentreY() {
        return centreY;
    }

    /**
     * Gets the value of the rx property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getRadiusX() {
        return radiusX;
    }

    /**
     * Gets the value of the ry property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getRadiusY() {
        return radiusY;
    }

    /**
     * Sets the value of the cx property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setCentreX(double value) {
        this.centreX = value;
    }

    /**
     * Sets the value of the cy property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setCentreY(double value) {
        this.centreY = value;
    }

    /**
     * Sets the value of the rx property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setRadiusX(double value) {
        this.radiusX = value;
    }

    /**
     * Sets the value of the ry property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setRadiusY(double value) {
        this.radiusY = value;
    }

    @Override
    protected void toStringDetail(ToStringHelper builder) {
        builder.add("cx", centreX);
        builder.add("cy", centreY);
        builder.add("rx", radiusX);
        builder.add("ry", radiusY);
        super.toStringDetail(builder);
    }

}
