//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.03.25 at 03:40:09 PM NZDT
//


package nz.co.ctg.jmsfx.svg.shape;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.google.common.base.MoreObjects.ToStringHelper;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "circle")
@XmlRootElement(name = "circle")
public class SvgCircle extends AbstractSvgShape {

    @XmlAttribute(name = "cx")
    protected double centreX;

    @XmlAttribute(name = "cy")
    protected double centreY;

    @XmlAttribute(name = "r", required = true)
    protected double radius;

    /**
     * Gets the value of the cx property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getCentreX() {
        return centreX;
    }

    /**
     * Sets the value of the cx property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setCentreX(double value) {
        this.centreX = value;
    }

    /**
     * Gets the value of the cy property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getCentreY() {
        return centreY;
    }

    /**
     * Sets the value of the cy property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setCentreY(double value) {
        this.centreY = value;
    }

    /**
     * Gets the value of the r property.
     *
     * @return
     *     possible object is
     *     {@link double }
     *
     */
    public double getRadius() {
        return radius;
    }

    /**
     * Sets the value of the r property.
     *
     * @param value
     *     allowed object is
     *     {@link double }
     *
     */
    public void setRadius(double value) {
        this.radius = value;
    }

    @Override
    protected void toStringDetail(ToStringHelper builder) {
        builder.add("cx", centreX);
        builder.add("cy", centreY);
        builder.add("r", radius);
        super.toStringDetail(builder);
    }

}
